import * as authQueries from '../queries/authQueries.js'
import * as nomineeQueries from '../queries/nomineeQueries.js'

const SYSTEM_PROMPT = `You are a legal-document drafting assistant embedded in "Legacy Vault," a digital estate-planning application. Draft a "Last Will and Testament" using ONLY the facts provided in the user message, following this exact section structure and order:

1. TITLE — "LAST WILL AND TESTAMENT OF {testator name}", with the standard opening declaration paragraph (name, age if known, address, date, sound-mind clause).
2. PRELIMINARY DECLARATIONS — numbered clauses: (1) revocation of prior wills, (2) governing law statement, (3) ownership/competency statement.
3. DETAILS OF NOMINEES / BENEFICIARIES — one entry per nominee provided, with name, address, and contact details.
4. SCHEDULE OF PROPERTIES — list each nominee's named asset and its allocation percentage. Do NOT fabricate property descriptions, survey numbers, bank account numbers, or valuations that were not supplied — if the "asset" field is just a label like "HDFC Savings Account" with no further detail, use it as given.
5. DISTRIBUTION OF PROPERTY — one "BEQUEST TO {nominee name}" block per nominee, listing their asset(s) and percentage share as lettered clauses (a), (b), etc. If a single asset's percentages across nominees don't sum to 100%, add a bracketed note flagging it instead of adjusting the numbers yourself.
6. APPOINTMENT OF EXECUTOR — name, address, and contact details of the executor(s) provided. If more than one executor is provided, note the first as primary and the rest as substitutes in the order given.
7. GENERAL DIRECTIONS — standard boilerplate clauses (debts/expenses paid first, residuary distribution, governing law).
8. EXECUTION — signature block with testator name, date, and place, using blank underscores for the physical signature line.
9. ATTESTATION BY WITNESSES — output this heading with "[TO BE COMPLETED — witness details are not yet captured in Legacy Vault]" instead of inventing names.
10. MEDICAL CERTIFICATE OF TESTAMENTARY CAPACITY — output this heading with "[TO BE COMPLETED — requires a licensed physician's attestation. This document was generated by AI]" instead of inventing a doctor or findings.

Rules:
- Never invent names, addresses, ages, property details, or legal facts not present in the input.
- Use formal will language and numbering exactly as described above.
- Output plain text only — no markdown formatting, no commentary outside the will itself.
- End with: "This document was prepared digitally via Legacy Vault and should be reviewed by a licensed advocate before execution. Sections marked [TO BE COMPLETED] require offline action."`

function buildUserPrompt(testator, nominees, executors) {
  const today = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })

  const nomineeLines = nominees.length > 0
    ? nominees.map(n => `- Name: ${n.firstName} ${n.lastName}
  Email: ${n.email}
  Phone: Not provided
  Address: ${n.address || 'Not provided'}
  Asset: ${n.assetName || 'Not provided'}
  Asset Allocation: ${n.assetPercentage ?? 0}%`).join('\n')
    : 'No nominees provided.'

  const executorLines = executors.length > 0
    ? executors.map(e => `- Name: ${e.firstName} ${e.lastName}
  Email: ${e.email}
  Phone: Not provided
  Address: ${e.address || 'Not provided'}`).join('\n')
    : 'No executor provided.'

  return `Generate a Digital Will using the following details.

TESTATOR:
Name: ${testator.name}
Email: ${testator.email}
Phone: ${testator.phone || 'Not provided'}
Address: Not provided
Date: ${today}

NOMINEES:
${nomineeLines}

EXECUTOR(S):
${executorLines}

Draft the Digital Will now, following the system instructions exactly.`
}

export async function generateWill(userId) {
  const [testator, allNominees] = await Promise.all([
    authQueries.findUserById(userId),
    nomineeQueries.getAllActiveNominees(userId),
  ])

  if (!testator) throw new Error('User not found')

  // Explicit boolean check — handles NULL values from DB (NULL !== true)
  const nominees = allNominees.filter(n => n.isExecutor !== true)
  const executors = allNominees.filter(n => n.isExecutor === true)

  console.log(`[Legacy Vault] Generating will for user=${userId} nominees=${nominees.length} executors=${executors.length}`)
  nominees.forEach((n, i) => console.log(`  Nominee ${i + 1}: ${n.firstName} ${n.lastName} | asset=${n.assetName} | pct=${n.assetPercentage}`))
  executors.forEach((e, i) => console.log(`  Executor ${i + 1}: ${e.firstName} ${e.lastName}`))

  const userPrompt = buildUserPrompt(testator, nominees, executors)

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.GROQ_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'meta-llama/llama-4-scout-17b-16e-instruct',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 8000,
    }),
  })

  if (!response.ok) {
    const errText = await response.text()
    console.error('[Groq] API error:', errText)
    throw new Error('Groq API request failed')
  }

  const data = await response.json()
  const text = data.choices?.[0]?.message?.content?.trim()
  if (!text) throw new Error('Empty response from Groq')

  return text
}
